### ISSUE TITLE
Attribute Error thrown when using Foscam HD - Override for C1

### ISSUE THREAD

**Issue by RaysceneNS** [maikito26/plugin.video.surveillanceroom#6]
> Error

 Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'super' object has no attribute 'init'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.surveillanceroom/default.py", line 272, in <module>
                                                main_menu()
                                              File "/storage/.kodi/addons/plugin.video.surveillanceroom/default.py", line 193, in main_menu
                                                camera = Camera(camera_number)
                                              File "/storage/.kodi/addons/plugin.video.surveillanceroom/resources/lib/ipcam_api_wrapper.py", line 38, in __init__
                                                self.camera = ipcam_api_foscamhd.FoscamCameraOverride(camera_settings, daemon, verbose)
                                              File "/storage/.kodi/addons/plugin.video.surveillanceroom/resources/lib/ipcam_api_foscamhd.py", line 808, in __init__
                                                super(FoscamCamera, self).init(camera_settings, daemon = False, verbose = True)
                                            AttributeError: 'super' object has no attribute 'init

**Comment by maikito26** [comment]
Thanks for pointing this out - I'll include a C1 specific configuration in the revamp once Kodi 18 hits.

**Comment by jasonbuechler** [comment]
I know this isn't the PERFECT place to put this comment, but given the situation, this seems next best thing for any active SR users who can't find "the thread" on the kodi forums -- IT'S GONE.  
....??!!!??  It *was* at https://forum.kodi.tv/showthread.php?tid=240768 but it appears there's been some kind of upheaval on those forums... possibly in overly-bitter response to streaming addons... and not just posts are gone: entire forums are gone.  !!!??!
As someone who just discovered this great addon, I'm hoping maikito26 can make a thread somewhere else for this?? Please and thanks!
